version: "3"

services:
  # Java Monolith Sample Application
  # demo:
  #   container_name: demo
  #   build: ./demo
  #   depends_on:
  #     - db
  #   ports:
  #     - "8080:8080"
  #   volumes:
  #     - ./demo:/srv
  #   tty: true
  #   working_dir: /srv
  #   environment:
  #     spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
  #     spring.datasource.url: "jdbc:mysql://db:3306/demo"
  #     spring.datasource.username: "mysql"
  #     spring.datasource.password: "mysql"
  #     OTEL_EXPORTER_OTLP_ENDPOINT: http://otel-collector:4317
  #     OTEL_SERVICE_NAME: spring-demo

  userapi:
    container_name: userapi
    build: ./userapi
    depends_on:
      - userdb
    ports:
      - "8081:8081"
    volumes:
      - ./userapi:/srv
    tty: true
    working_dir: /srv
    environment:
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://userdb:3306/user"
      spring.datasource.username: "mysql"
      spring.datasource.password: "mysql"

  # MySQL
  userdb:
    container_name: userdb
    build: ./userdb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: user
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
      TZ: "Asia/Tokyo"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - ./userdb/initdb/:/docker-entrypoint-initdb.d/
      - ./userdb/config:/etc/mysql/conf.d
    ports:
      - 3306:3306
