spring:
  datasource:
    driverClassName: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/web"
    username: "mysql"
    password: "mysql"

mybatis:
  configuration:
    map-underscore-to-camel-case: true

# logging:
#   pattern:
#     level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p

---
spring.config.activate.on-profile: docker

spring.datasource:
  url: "jdbc:mysql://mysql:3306/web"
